---
name: build oiio for windows

on:
  push:
    branches: ["test-ci"]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install visualstudio
      run: |
        choco install visualstudio2019buildtools
        choco install visualstudio2019-workload-vctools
        choco install visualstudio2019-workload-manageddesktop

    - name: install oiio using vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.bat
        ./vcpkg/vcpkg.exe install openimageio[tools]

    - name: test oiiotool.exe
      run: ./vcpkg/installed/x64-windows/tools/openimageio/oiiotool.exe --help

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: oiio-tools-windows-2.5.8.0
        path: ./vcpkg/installed/x64-windows/tools/openimageio
