---
name: build oiio for windows

on:
  push:
    branches: ["test-ci"]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install visualstudio
      run: |
        choco install visualstudio2022buildtools
        choco install visualstudio2022-workload-vctools
        choco install visualstudio2022-workload-manageddesktop

    - name: install cmake
      run: |
        choco install cmake --installargs "ADD_CMAKE_TO_PATH=System"

    - name: build with oiio_win_batch
      run: |
        git clone https://github.com/BrianHanke/oiio_win_batch.git
        ./oiio_win_batch/oiio.bat
