---
name: build oiio for windows

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install visualstudio
      run: |
        choco install visualstudio2017buildtools --version=15.9.41.0
        choco install visualstudio2017-workload-vctools --version=1.3.1
        choco install visualstudio2017-workload-manageddesktop --version=1.2.1

    - name: install oiio using vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.bat
        ./vcpkg/vcpkg.exe install openimageio[tools]

    - name: test oiiotools.exe
      run: .\vcpkg\installed\x64-windows\tools\bin\oiiotool.exe

    - name: zip tools
      shell: pwsh
      run: Compress-Archive -Path vcpkg\installed\x64-windows\tools\bin\openimageio -DestinationPath oiio-tools.zip

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: oiio-tools
        path: oiio-tools.zip
